version: '3'
services:

  mongodb:
    container_name: 'mongodb'
    image: mongo:latest
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27018:27018"
    networks:
      - default

  server:
    container_name: 'post-server'
    restart: always
    environment:
      - PORT=8001
      - MONGO_URL=mongodb://mongodb:27018/posts
      - JWT_SECRET=jwtjwtjwt
      - SESSION_SECRET=secret
      - API_ID=6840255
      - API_SECRET=ZPzNN6CbXG3fQSM8SNKg
    volumes:
      - ./admin_backend:/opt/app
    ports:
      - "8001:8001"
    build:
      dockerfile: Dockerfile
      context: admin_backend/.
    networks:
      - default
    deploy:
      replicas: 1
    depends_on:
      - mongodb
    links:
      - mongodb


  client:
   container_name: 'post-client'
   restart: always
   volumes:
     - ./admin_frontend:/opt/app
   ports:
     - "3000:3000"
   build:
     dockerfile: Dockerfile
     context: admin_frontend/.
   networks:
     - default
   deploy:
     replicas: 1
   depends_on:
     - server
   links:
     - server
